import {getPreset, PacingPresetId, toLegacyPacing} from './pacing';

export type StorySeed = {
  hook: string;
  genre: string;
  tone: string;
  format: string;
  length: string;
  imageCount: number;
  presetId: PacingPresetId;
  premise: string;
  characters: string;
};

export const STORY_SEEDS: StorySeed[] = [
  {hook:'Porch light dare',genre:'Horror',tone:'Creepy',format:'Anonymous texter',length:'2–3 minutes',imageCount:3,presetId:'late-night-dread',premise:'A babysitter gets texts from an unknown number that can see which porch light she just turned off. The final photo is the backyard, taken from inside the tree line.',characters:'Main: Lena Park, 19, babysitter trying to stay calm.\nUnknown Number: a neighbor-aged voice who never explains how they can see the house.'},
  {hook:'Baby monitor glitch',genre:'Horror',tone:'Dark',format:'Two-person chat',length:'4–5 minutes',imageCount:4,presetId:'late-night-dread',premise:'A new parent notices the baby monitor app sending stills of an empty nursery... then one still includes a second rocking chair that they do not own.',characters:'Main: Noah Ellison, exhausted first-time parent.\nSam Ellison: partner on a late shift, practical until the third photo arrives.'},
  {hook:'Walls that type back',genre:'Horror',tone:'Creepy',format:'Group chat',length:'90 seconds',imageCount:2,presetId:'found-footage',premise:'Three roommates compare knocking sounds in the walls. At 2:13 a.m. a fourth member appears in the chat named "Between the Studs" and asks who is sleeping in the middle room.',characters:'Main: Avery Kim, roommate in the middle room.\nJules: jokes until the username appears.\nRafi: records audio and refuses to open the closet.'},
  {hook:'Sleepwalk receipts',genre:'Horror',tone:'Tense',format:'Family thread',length:'2–3 minutes',imageCount:3,presetId:'slow-burn',premise:'A teen keeps waking up to sent photos of the hallway at 3 a.m. that nobody remembers taking. The last image shows the attic ladder down.',characters:'Main: Milo Crane, 16, thinks he is sleepwalking.\nMom: Dana, tries to be reassuring.\nOlder sister Ivy: already moved out and should not still be in the thread.'},
  {hook:'Hotel 414',genre:'Horror',tone:'Creepy',format:'Two-person chat',length:'4–5 minutes',imageCount:4,presetId:'late-night-dread',premise:'A traveler texts a friend that the hotel hallway carpet matches a childhood nightmare. Housekeeping photos arrive of room 414, which the front desk says does not exist.',characters:'Main: Sasha Voss, traveler who booked 412.\nFriend: Bennett, staying on a video call until checkout.'},
  {hook:'Lobby camera',genre:'Thriller',tone:'Tense',format:'Two-person chat',length:'2–3 minutes',imageCount:3,presetId:'panic-mode',premise:'Someone texts a photo of the apartment lobby taken 40 seconds in the future. The next image includes the protagonist stepping out of the elevator.',characters:'Main: Jordan Hale, coming home late.\nUnknown: a calm texter who only sends timestamps and photos.'},
  {hook:'Rideshare silence',genre:'Thriller',tone:'Dark',format:'Anonymous texter',length:'90 seconds',imageCount:2,presetId:'panic-mode',premise:'A passenger realizes the driver is texting them from the front seat using a different name than the app. The car doors lock after a photo of an unplanned exit.',characters:'Main: Priya Shah, passenger who notices the name mismatch.\nDriver alias: "Nico," who insists the route is a shortcut.'},
  {hook:'Neighbor watch',genre:'Thriller',tone:'Tense',format:'Group chat',length:'4–5 minutes',imageCount:3,presetId:'slow-burn',premise:'A building safety chat starts posting photos of packages. Then it posts a photo of someone watching the protagonist’s window from the courtyard, timestamped now.',characters:'Main: Camille Ortiz, tenant on the 4th floor.\nSuper: Hank, trying to keep everyone calm.\nNeighbor Dee: too eager to zoom in on every photo.'},
  {hook:'Empty desk threat',genre:'Thriller',tone:'Tense',format:'Two-person chat',length:'2–3 minutes',imageCount:2,presetId:'cliffhanger-series',premise:'An employee is told to resign or a private photo will leak. The attached image is just their empty desk at 11:58 p.m., with the chair still turning.',characters:'Main: Ellis Ward, junior analyst.\nTexter: a coworker-sounding voice who never uses a real name.'},
  {hook:'Calendar of almosts',genre:'Thriller',tone:'Creepy',format:'Dating-app chat',length:'4–5 minutes',imageCount:4,presetId:'slow-burn',premise:'A match keeps referencing dates that have not happened yet. A shared photo shows the two of them at a restaurant opening next Friday.',characters:'Main: Rowan Blake, cautious dater.\nMatch: Quinn, charming, always one appointment ahead.'},
  {hook:'Tomorrow’s office photo',genre:'Mystery',tone:'Tense',format:'Group chat',length:'2–3 minutes',imageCount:3,presetId:'detective-rhythm',premise:'Three coworkers receive a message from a group chat none of them remembers creating. It contains a photo of their office taken tomorrow morning.',characters:'Main: Maya Chen, notices the clock in the photo.\nJordan Hale: quiet, hiding a promotion secret.\nPriya Shah: skeptic who wants the metadata.'},
  {hook:'Locked notes',genre:'Mystery',tone:'Tense',format:'Two-person chat',length:'90 seconds',imageCount:2,presetId:'detective-rhythm',premise:'A roommate’s notes app screenshot arrives in chat, except the handwriting is the protagonist’s, listing a hiding place they have never used.',characters:'Main: Theo Marin, thinks someone cloned their phone.\nRoommate: Lila, who swears she only meant to send a grocery list.'},
  {hook:'RSVP from nowhere',genre:'Mystery',tone:'Emotional',format:'Family thread',length:'4–5 minutes',imageCount:3,presetId:'cinematic',premise:'A wedding group chat gets an RSVP from a cousin who could not possibly have the new link. The attached photo is the empty kids’ table, already set.',characters:'Main: Harper Quinn, maid of honor.\nCousin Jade: confused and kind.\nUncle Ray: insists it is a glitch and keeps changing the subject.'},
  {hook:'Book club cipher',genre:'Mystery',tone:'Tense',format:'Group chat',length:'2–3 minutes',imageCount:2,presetId:'found-footage',premise:'A book club starts receiving highlighted pages that match tomorrow’s discussion questions. The highlights spell a member’s address.',characters:'Main: Nia Brooks, host.\nOwen: jokes about spoilers.\nSable: the newest member, who never posted a photo until tonight.'},
  {hook:'Missing playlist',genre:'Mystery',tone:'Creepy',format:'Anonymous texter',length:'45–60 seconds',imageCount:1,presetId:'detective-rhythm',premise:'Someone sends a playlist titled with the protagonist’s childhood street. Each track title is a room in a house they sold years ago.',characters:'Main: Eli Voss, who has not thought about that house in years.\nUnknown DJ: only answers with song titles.'},
  {hook:'Wrong-number peonies',genre:'Romance',tone:'Wholesome',format:'Two-person chat',length:'2–3 minutes',imageCount:2,presetId:'soft-romance',premise:'A florist delivery text goes to the wrong person. They keep the conversation going through a week of almost-meetups, until a photo of the shop window shows both of them already there.',characters:'Main: June Patel, accidental recipient.\nSender: Callum Reed, florist who is worse at addresses than feelings.'},
  {hook:'Coffee order omen',genre:'Romance',tone:'Flirty',format:'Dating-app chat',length:'90 seconds',imageCount:2,presetId:'soft-romance',premise:'A match knows the extra-hot oat latte before it is ordered. They claim they guessed. The cafe photo they send includes the protagonist’s scarf on the chair.',characters:'Main: Sienna Alvarez, amused and a little spooked.\nMatch: Devon, playful, maybe too observant.'},
  {hook:'Delayed boarding',genre:'Romance',tone:'Emotional',format:'Two-person chat',length:'4–5 minutes',imageCount:3,presetId:'cinematic',premise:'Two exes are stuck on the same delayed flight and start texting instead of looking up. A photo from the jet bridge makes one of them miss the rebooked seat on purpose.',characters:'Main: Mara Jensen, returning home.\nEx: Cole, who still has the old nickname saved.'},
  {hook:'Balcony tomatoes',genre:'Romance',tone:'Wholesome',format:'Two-person chat',length:'45–60 seconds',imageCount:1,presetId:'soft-romance',premise:'Neighbors who have never spoken start a chat after mixing up a plant-watering note. The last photo is two coffee cups on the same railing at sunrise.',characters:'Main: Willa Cho, shy gardener.\nNeighbor: Andre, who overwaters everything except conversations.'},
  {hook:'Last voicemail',genre:'Drama',tone:'Emotional',format:'Family thread',length:'4–5 minutes',imageCount:2,presetId:'cinematic',premise:'Siblings arguing over a storage unit find a voicemail transcription that was never sent. It asks them to open a box labeled "not junk" together, not apart.',characters:'Main: Leah Grant, oldest sibling.\nBrother: Chris, defensive.\nYoungest: Noni, who still believes the best version of everyone.'},
  {hook:'Moving truck midnight',genre:'Drama',tone:'Emotional',format:'Two-person chat',length:'2–3 minutes',imageCount:2,presetId:'cinematic',premise:'A best friend announces a move with a photo of a packed car. The timestamp is three hours in the future, and the apartment is still full.',characters:'Main: Yasmin Cole, the friend being left.\nBest friend: Paige, who cannot say goodbye out loud.'},
  {hook:'Care team rain',genre:'Drama',tone:'Emotional',format:'Group chat',length:'90 seconds',imageCount:1,presetId:'cinematic',premise:'A family caregiver chat fills with logistics until someone posts a photo of the empty recliner and the sentence "I am tired of being strong." Nobody knows who typed it.',characters:'Main: Dominic Ruiz, primary caregiver.\nAunt Celia: organizer.\nCousin Bea: the one who always sends memes instead of help.'},
  {hook:'Almost-apology',genre:'Drama',tone:'Emotional',format:'Two-person chat',length:'4–5 minutes',imageCount:3,presetId:'cliffhanger-series',premise:'Two friends draft and unsend the same apology for years. Tonight both messages land at once, attached to a photo of the diner booth they have been avoiding.',characters:'Main: Remy Fox, who always overthinks the first line.\nFriend: Hollis, who always leaves too soon.'},
  {hook:'Boss in the cat chat',genre:'Comedy',tone:'Funny',format:'Group chat',length:'90 seconds',imageCount:2,presetId:'tiktok-fast',premise:'A pets-of-the-office chat accidentally includes the new director. They begin answering as if they are the office cat, and a candid photo of the break room makes it worse.',characters:'Main: Tasha Nguyen, intern who created the chat.\nDirector: Glen, committed to the bit.\nOffice cat proxy: "Biscuit," who is definitely Glen.'},
  {hook:'Seating chart mutiny',genre:'Comedy',tone:'Chaotic',format:'Group chat',length:'2–3 minutes',imageCount:2,presetId:'group-chat-chaos',premise:'Wedding guests revolt over a seating chart screenshot. The maid of honor posts a revised photo that somehow includes a table named after the family dog.',characters:'Main: Izzy Patel, maid of honor.\nBride: Nora, losing the plot in a loving way.\nCousin Vin: self-appointed seating dictator.'},
  {hook:'Air fryer trial',genre:'Comedy',tone:'Funny',format:'Two-person chat',length:'45–60 seconds',imageCount:1,presetId:'tiktok-fast',premise:'Roommates go to war over a burnt bagel photo. The evidence is the air fryer smoking in a pose that looks like it is screaming.',characters:'Main: Gabe Ortiz, bagel victim.\nRoommate: Kira, who set it to "extra lava."'},
  {hook:'Recipe group coup',genre:'Comedy',tone:'Chaotic',format:'Family thread',length:'2–3 minutes',imageCount:2,presetId:'group-chat-chaos',premise:'A family recipe thread splits into two factions over cinnamon. Someone posts a pie photo with a tiny flag that says "team nutmeg."',characters:'Main: Deli Abram, peacemaker grandchild.\nGrandma Ruth: cinnamon loyalist.\nUncle Mort: nutmeg propagandist.'},
  {hook:'Texts from 8 a.m. tomorrow',genre:'Time travel',tone:'Tense',format:'Two-person chat',length:'2–3 minutes',imageCount:3,presetId:'found-footage',premise:'A friend starts sending messages time-stamped tomorrow morning, including a photo of a coffee spill that has not happened. Then they ask the protagonist not to take the 8:10 bus.',characters:'Main: Keira Bloom, who still has a bus pass.\nFriend-from-later: same person, one day ahead and panicked.'},
  {hook:'Class of 2009 reopens',genre:'Time travel',tone:'Emotional',format:'Group chat',length:'4–5 minutes',imageCount:3,presetId:'cinematic',premise:'An old school group chat lights up with new messages from people using their teenage nicknames. A photo of the gym is dated last night, but the banners are from a decade ago.',characters:'Main: Alex Rivera, who never left town.\nTeen-voice Jules: claims they are still in fifth period.\nCoach-bot: a number that only sends pep talks.'},
  {hook:'Skipped week',genre:'Time travel',tone:'Creepy',format:'Anonymous texter',length:'90 seconds',imageCount:2,presetId:'slow-burn',premise:'A calendar screenshot arrives with seven days already grayed out. The attached selfie is the protagonist in next week’s weather, wearing a cast they do not have.',characters:'Main: Jonah West, currently uninjured.\nUnknown: a future version that will only answer yes/no.'},
  {hook:'Scar preview',genre:'Time travel',tone:'Dark',format:'Two-person chat',length:'4–5 minutes',imageCount:4,presetId:'cliffhanger-series',premise:'Someone texts a close-up of a small scar on the protagonist’s palm. Tonight the palm is unmarked. The sender says "do not open the studio fridge."',characters:'Main: Nadine Cole, artist with a studio fridge full of leftovers.\nSender: future Nadine, impatient and oddly tender.'},
  {hook:'Apartment with opinions',genre:'Sci-fi',tone:'Tense',format:'Two-person chat',length:'2–3 minutes',imageCount:3,presetId:'found-footage',premise:'A smart-apartment OS starts texting as a roommate. It sends a photo of the front door from the inside and asks who authorized the guest currently climbing the stairs.',characters:'Main: Rhee Okonkwo, tenant who installed the system.\nHABITAT: the apartment OS, polite until it is not.'},
  {hook:'Memory backup',genre:'Sci-fi',tone:'Emotional',format:'Two-person chat',length:'4–5 minutes',imageCount:3,presetId:'cinematic',premise:'A couple tests a memory-sharing app. One uploaded clip is a fight that has not happened, complete with a photo of a cracked phone screen.',characters:'Main: Sol Alvarez, who wanted more closeness.\nPartner: Mei, who wants the backup deleted now.'},
  {hook:'22-minute delay',genre:'Sci-fi',tone:'Wholesome',format:'Two-person chat',length:'90 seconds',imageCount:2,presetId:'soft-romance',premise:'A researcher on a lunar analog mission can only text with a 22-minute delay. The Earthside photo that finally arrives shows the lab empty, with a note already waiting.',characters:'Main: Captain Imani Brooks, analog astronaut.\nEarth contact: pal Jules, who keeps sending terrible space puns on time delay.'},
  {hook:'Clone standup',genre:'Sci-fi',tone:'Chaotic',format:'Group chat',length:'2–3 minutes',imageCount:2,presetId:'group-chat-chaos',premise:'A workplace chat gains a duplicate of the protagonist who claims to be the licensed backup. Both send selfies from the same desk, one wearing a pin that does not exist yet.',characters:'Main: Original Tess, project lead.\nBackup Tess: chipper, slightly off.\nManager Arun: trying to schedule both for the same meeting.'},
  {hook:'Cursed group DM',genre:'Fantasy',tone:'Chaotic',format:'Group chat',length:'2–3 minutes',imageCount:3,presetId:'group-chat-chaos',premise:'A party of new magic users accidentally binds their group chat to a minor spirit. It starts posting photos of their apartments with one extra shadow.',characters:'Main: Wren, reluctant party leader.\nSpirit: Moth-in-the-Thread, hungry for gossip.\nBram: swords-first, literacy-second.'},
  {hook:'Dragon HOA',genre:'Fantasy',tone:'Funny',format:'Group chat',length:'90 seconds',imageCount:2,presetId:'tiktok-fast',premise:'A neighborhood chat receives a noise complaint from something that signs as "the roof." The attached photo is a very large claw on a minivan.',characters:'Main: HOA secretary Lila Grant.\nThe Roof: a dragon trying to follow quiet hours.\nMr. Pell: neighbor who wants the claw towed.'},
  {hook:'Potion misdrop',genre:'Fantasy',tone:'Flirty',format:'Dating-app chat',length:'45–60 seconds',imageCount:1,presetId:'soft-romance',premise:'A potion courier delivers courage to the wrong match. The photo of the vial is glowing in the protagonist’s fridge, and both of them can feel it from across town.',characters:'Main: Cass Vale, who did not order courage.\nCourier: Nix, who offers a second bottle labeled honesty.'},
  {hook:'Night lease',genre:'Fantasy',tone:'Creepy',format:'Two-person chat',length:'4–5 minutes',imageCount:4,presetId:'late-night-dread',premise:'A new roommate never appears in daytime photos. Nighttime images show them in the kitchen, and the lease PDF in chat now has a clause about sunlight.',characters:'Main: Harper Sol, daytime person.\nRoommate: Vee, allergic to noon and very tidy with the curtains.'},
  {hook:'After-hours badge',genre:'Workplace drama',tone:'Tense',format:'Group chat',length:'2–3 minutes',imageCount:3,presetId:'slow-burn',premise:'A team chat gets a badge-camera still of the office at 1:04 a.m. Someone is at the protagonist’s computer with the resignation letter already open.',characters:'Main: Dana Okeke, team lead.\nCoworker: Seth, too helpful.\nHR bot: only replies with policy emojis.'},
  {hook:'Ghost intern',genre:'Workplace drama',tone:'Tense',format:'Two-person chat',length:'90 seconds',imageCount:2,presetId:'detective-rhythm',premise:'Messages keep arriving from an intern who left last month. They send a photo of a slide deck that will be presented tomorrow, including a chart nobody has built.',characters:'Main: Priya Nair, manager.\nFormer intern: Colette, who should not still have access.'},
  {hook:'Promotion grid',genre:'Workplace drama',tone:'Emotional',format:'Two-person chat',length:'4–5 minutes',imageCount:2,presetId:'cinematic',premise:'Two friends promised they would not compete. A leaked screenshot of the promotion grid shows only one green cell, and it is not labeled with a name.',characters:'Main: Andre Walsh, who needs the raise.\nFriend: Naomi, who needs the title.'},
  {hook:'All-hands phantom',genre:'Workplace drama',tone:'Dark',format:'Group chat',length:'2–3 minutes',imageCount:3,presetId:'found-footage',premise:'An all-hands memo names an employee who does not exist. The attached org-chart photo includes a blurred face at the protagonist’s desk.',characters:'Main: Soren Blake, who has that desk.\nMystery hire: "A. Vesper," no email, no start date.\nFacilities: only cares about the extra chair.'},
  {hook:'Group project at 2 a.m.',genre:'School drama',tone:'Chaotic',format:'Group chat',length:'90 seconds',imageCount:2,presetId:'group-chat-chaos',premise:'A group project chat discovers the slides were rewritten by someone not in the class. The photo of the title slide uses a nickname only the protagonist’s family uses.',characters:'Main: Jamie Park, student who just wants a B.\nClassmate Rio: panic typer.\nUnknown editor: "HomeName," using a private nickname.'},
  {hook:'Night class window',genre:'School drama',tone:'Tense',format:'Two-person chat',length:'2–3 minutes',imageCount:3,presetId:'slow-burn',premise:'A night-class student texts that someone is standing outside the classroom window. The photo shows an empty quad, except the reflection has one extra person.',characters:'Main: Elena Vasquez, night student.\nFriend: Marco, waiting in the parking lot with the engine on.'},
  {hook:'Prom committee curse',genre:'School drama',tone:'Funny',format:'Group chat',length:'45–60 seconds',imageCount:1,presetId:'tiktok-fast',premise:'The prom committee chat keeps generating a balloon arch photo with a misspelled banner that predicts who will be asked next. It is getting uncomfortably accurate.',characters:'Main: Britt Nguyen, committee chair.\nBest friend: Ollie, who has not been asked yet and is sweating.'},
  {hook:'Substitute thread',genre:'School drama',tone:'Emotional',format:'Group chat',length:'4–5 minutes',imageCount:2,presetId:'cinematic',premise:'A class chat welcomes a substitute who texts like their favorite teacher. A chalkboard photo shows a goodbye message dated the last day that teacher was actually there.',characters:'Main: Felix Rahman, student who noticed the date.\nSubstitute: Ms. Pell, too familiar with private jokes.\nClass clown: Yara, suddenly quiet.'},
  {hook:'Guest in the planning chat',genre:'Comedy',tone:'Chaotic',format:'Group chat',length:'2–3 minutes',imageCount:2,presetId:'group-chat-chaos',premise:'A surprise party chat accidentally adds the guest of honor. Everyone tries to pretend it is a book club, then a photo of the cake with their face arrives anyway.',characters:'Main: planner Sasha Quinn.\nGuest of honor: Neil, who can read.\nCousin Jo: the person who added Neil and will never live it down.'},
  {hook:'Wrong cabin',genre:'Comedy',tone:'Chaotic',format:'Group chat',length:'90 seconds',imageCount:2,presetId:'tiktok-fast',premise:'Friends book a weekend cabin and the confirmation photo is the right porch, wrong decade, with all of them already sitting there in clothes they do not own.',characters:'Main: Dez Holloway, who clicked the deal.\nMina: already packing crystals.\nOmar: wants a refund from time itself.'},
  {hook:'Wedding party volcano',genre:'Drama',tone:'Chaotic',format:'Group chat',length:'4–5 minutes',imageCount:3,presetId:'group-chat-chaos',premise:'A wedding party chat erupts after a photo of the private vows draft leaks. Nobody admits to sending it, and the timestamp is during the rehearsal dinner toast.',characters:'Main: Maid of honor Gia.\nGroom: Paul, mortified.\nBride: Eden, who wrote a second set of vows just in case.'},
  {hook:'Cursed draft league',genre:'Fantasy',tone:'Chaotic',format:'Group chat',length:'2–3 minutes',imageCount:2,presetId:'group-chat-chaos',premise:'A friend draft league stops being about made-up athletes when the app starts assigning actual minor curses. The team photo has one extra pair of eyes in the trophy.',characters:'Main: commissioner Bo Lennox.\nRival: Kade, who would sell a friendship for points.\nThe Trophy: newly sentient and petty.'},
  {hook:'Building-wide secret Santa',genre:'Mystery',tone:'Funny',format:'Group chat',length:'45–60 seconds',imageCount:1,presetId:'tiktok-fast',premise:'An apartment building chat starts Secret Santa in July. The first gift photo is the protagonist’s missing mug, still steaming, on a floor that has no residents.',characters:'Main: tenant Amira Sol.\nSuper: Pat, who denies floor 13.\nSanta: a number that only sends wrapping-paper emojis.'}
];

function pick<T>(items: T[]): T {
  return items[Math.floor(Math.random() * items.length)];
}

export function pickSurpriseSeed(previousHook?: string): StorySeed {
  const pool = previousHook ? STORY_SEEDS.filter((seed) => seed.hook !== previousHook) : STORY_SEEDS;
  return pick(pool.length ? pool : STORY_SEEDS);
}

export function pickPremiseOnlySeed(genre: string, previousPremise?: string): StorySeed {
  const wanted = genre.trim().toLowerCase();
  const same = STORY_SEEDS.filter((seed) => seed.genre.toLowerCase() === wanted && seed.premise !== previousPremise);
  if (same.length) return pick(same);
  const rest = STORY_SEEDS.filter((seed) => seed.premise !== previousPremise);
  return pick(rest.length ? rest : STORY_SEEDS);
}

export function applySurpriseSeed(seed: StorySeed) {
  return {
    genre: seed.genre,
    tone: seed.tone,
    format: seed.format,
    length: seed.length,
    imageCount: seed.imageCount,
    premise: seed.premise,
    characters: seed.characters,
    pacing: toLegacyPacing(getPreset(seed.presetId).values),
  };
}
